# Generated by Django 3.2.4 on 2021-07-15 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20210713_0951'),
        ('posts', '0003_auto_20210715_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='added_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='added_by',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='profiles.profile'),
        ),
    ]
