# Generated by Django 3.2.4 on 2021-07-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='track_artist',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='update',
            name='track_img',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='update',
            name='track_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
